		<tr>
			<th colspan="4" class="title">财务报表</th>
		</tr>
		@if(empty($sjbg1))
		<tr>
			<th rowspan="4">
				@if($sjbg1->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sjbg1->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sjbg1->zzc}}</td>
			<td>{{$sjbg1->zfz}}</td>
			<td>{{$sjbg1->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sjbg1->yysl}}</td>
			<td>{{$sjbg1->yylr}}</td>
			<td>{{$sjbg1->jlr}}</td>
		</tr>
		@endif
		@if(empty($sjbg2))
		<tr>
			<th rowspan="4">
				@if($sjbg2->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sjbg2->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sjbg2->zzc}}</td>
			<td>{{$sjbg2->zfz}}</td>
			<td>{{$sjbg2->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sjbg2->yysl}}</td>
			<td>{{$sjbg2->yylr}}</td>
			<td>{{$sjbg2->jlr}}</td>
		</tr>
		@endif
		@if(empty($sjbg3))
		<tr>
			<th rowspan="4">
				@if($sjbg3->ywwftg == '1')
					业务无法提供
				@else
					财务报表日期<br>
					{{$sjbg3->year}}
				@endif
			</th>
			<th>资产总额(万元)</th>
			<th>负债总额(万元)</th>
			<th>净资产(所有者权益)(万元</th>
		</tr>
		<tr>
			<td>{{$sjbg3->zzc}}</td>
			<td>{{$sjbg3->zfz}}</td>
			<td>{{$sjbg3->syzqy}}</td>
		</tr>
		<tr>
			<th>营业收入(万元)</th>
			<th>利润总额(万元)</th>
			<th>净利润(万元)</th>
		</tr>
		<tr>
			<td>{{$sjbg3->yysl}}</td>
			<td>{{$sjbg3->yylr}}</td>
			<td>{{$sjbg3->jlr}}</td>
		</tr>
		@endif